POST http://localhost:3003/project/create
Content-Type: application/json

{
    "title": "Projeto 5",
    "description": "testando projeto 5"
}
###
GET http://localhost:3003/project

###
GET http://localhost:3003/project/d5f8c626-04cb-4633-89da-b997e7dd9f63